### ISSUE TITLE
Custom Fields are semi broken since today

### ISSUE THREAD

**Issue by mirai-ux** [killergerbah/asbplayer#411] opened 2024-04-21 08:54 UTC
Since the latest commit asbplayer custom fields seem to have been broken. My entire config got erased, and due to my own stupidity my backup was old enough that I had to change some of the custom fields. Well, for some reason now they automatically get sorted in an alphabetical order, so I could create fields: Target Word 1; Reading 1; Definition 1, all in this particular order, only for Reading to immediatly jump ahead of Target Word, and Definition ahead of them both.

**Comment by killergerbah** [comment] 2024-04-21 22:36
Do you mind uploading a video of the problem? I can't seem to reproduce it and it would be helpful to know the exact steps you're taking.

**Comment by mirai-ux** [comment] 2024-04-22 07:07
https://github.com/killergerbah/asbplayer/assets/129323414/2ea9813c-3fc5-44aa-97ad-e4ec40c69432

Every time i turn on the browser (using vivaldi because ff codec support is _not great TM_) the fields just get sorted alphabetically. I have to import my json file for it to work normally. Closing and reopening the app breaks it all over again

**Comment by killergerbah** [comment] 2024-04-22 07:50
I would guess that it was a Vivaldi update (although even if that is the case, this is pretty baffling behavior). I did release some code a couple days ago, but no changes were made to the settings UI, at least none that would cause an issue like this. I'll still take a look to verify these claims and see if there are any workarounds.

**Comment by killergerbah** [comment] 2024-04-22 08:07
Okay, I believe I know why this issue might be happening. The custom Anki fields settings don't have any ordering data and so the order in which they appear in the settings UI or Anki dialog is entirely dependent on how the browser decides to sort the dictionary when retrieving it from storage. So this is not entirely a problem with the browser (it happens on Chrome too if you refresh the page) since the data model itself is flawed and doesn't preserve ordering. The only thing that confuses me is why it hasn't appeared until now. 

I think a fix for this might be somewhat complicated and a little risky since I will need to settings data to a new data model. So you may have to live with this for some time. The workaround I would suggest is to put numbers in front of the field names for your custom fields.

**Closed** 2024-06-17 01:54 UTC
Labels: bug
