### ISSUE TITLE
Manually taking screenshot (Ctrl+Shift+V) is not working when watching local videos on 'killergerbah.github.io/asbplayer' (despite having the extension installed)

### ISSUE THREAD

**Issue by Y-LBG** [killergerbah/asbplayer#238] opened 2023-05-03 16:26 UTC
Hi @killergerbah,

I'm not sure if that's a bug, or a not-yet-implemented feature.

This is regarding the capability to manually take a screenshot, rather than hoping the image fitting the beginning of the subtitle will be good enough. Quite an amazing feature proposed by the asbplayer extension, since the proper image describing the action usually tends to arrive just a few seconds later.
However, while it seems to work fine on streamed videos (I checked on Youtube), this is not working when watching local videos on 'killergerbah.github.io/asbplayer'.

I do have the extension installed, so I'd have expected this "extension only" feature would be available but...

I also noticed that the 'Screenshot capture delay' feature proposed in the extension isn't working on 'killergerbah.github.io/asbplayer' either (which I'm guessing is directly tied to the previously mentionned issue)

Cheers

**Comment by killergerbah** [comment] 2023-05-06 02:53
@Y-LBG That's correct - screenshot delay and "manually take screenshot" features are not implemented on the site side. One reason for this is that any cards mined from the site will use the current frame for the screenshot, so in some sense "manually take screenshot" as a separate command isn't really necessary for the site. However I realize that this is inconsistent w/ the extension mining flow and in some cases the extension flow would be preferable. Since you're bringing this problem up now it may make more sense to make both flows more similar.

**Comment by Y-LBG** [comment] 2023-05-06 10:50
Interesting.

I was actually thiking about that as a potential enhancement : Using the current frame for the screenshot.
I do believe this is indeed the best from a UX perspective (rather than having to manually edit it again with Ctrl+Shift+V afterwards)

But you tell me this should already the case...
Yet, at least as per my tests, it doesn't seem to be working that way.
Even on the website, when I hit Ctrl+Shit+X or Ctrl+Shit+U, it uses the frame corresponding to the beginning of the subtitle for the screenshot.
There might be a **bug** there.

As for the **enhancement** to make both flows (website and extension) similar...
Only my opinion here, but I'd definitley say the best would be a mix of both worlds:

- _Default_: Use the current frame (rather than the frame corresponding to the beginning of the subtitle, which very rarely fits)
- _Possibility_: Ctrl+Shit+V to overwrite the above default behaviour (i.e. use whatever frame you want, even if before/after the subtitle/audio)

Cheers.

**Comment by killergerbah** [comment] 2023-05-06 15:06
@Y-LBG You're right, it looks I broke the "current frame" behavior at some point. I've pushed the fix for that; let me know what you think.

I think your suggestion for Ctrl+Shift+V makes sense. If anything it will make the UX more consistent and less confusing between the site and the extension, and it's a convenient way to open the last card.

**Comment by killergerbah** [comment] 2023-05-07 15:32
@Y-LBG Interesting I'm not able to reproduce that error on https://killergerbah.github.io/asbplayer/ 
What specifically are you doing to trigger it? And if possible could you paste a log here as well?

**Comment by Y-LBG** [comment] 2023-05-07 18:38
Can't reproduce anymore either...
Was getting a 404 on the mp3-converter.js
Might have just been a cache issue on my client.
気にしないで；」

**Comment by killergerbah** [comment] 2023-05-07 20:08
I see, that makes sense

**Comment by killergerbah** [comment] 2023-05-28 01:52
This is implemented in the `localization` branch.

**Closed** 2023-05-31 03:21 UTC
Labels: enhancement

**Comment by Y-LBG** [comment] 2023-06-02 09:46
Nice =D
Looking forward to that ;]
