### ISSUE TITLE
Netflix bug that break the player

### ISSUE THREAD

**Issue by nzarbayezid** [killergerbah/asbplayer#136] opened 2022-04-14 23:46 UTC
There is a bug that causes the Netflix to be annoying, and it's happening while watching a movie that has a 16:9 aspect ratio (most of the movies use that aspect ratio), a white bar appears on the right side of the web that will let you scroll down and break the player, it's so anyone that even brake your immersion, but it will not happening when the movie is 1:1 aspect ratio

I tried to explain the bug in this [video ](https://youtu.be/-Rj8CaCF7WM)so you can fix it as soon as possible

yes I disabled all the other extensions and try to reinstall your extension there was no hope

![image](https://user-images.githubusercontent.com/101425664/163494202-0a953b70-fe4d-4688-894e-83f2b642f2c1.png)

**Comment by killergerbah** [comment] 2022-04-15 00:37
@nzarbayezid Thanks for the report. I've seen this before - will take a look again.

**Comment by killergerbah** [comment] 2022-04-15 03:00
@nzarbayezid The only way I can consistently reproduce this is if the subtitle offset from the bottom of the player is too low. Can you try setting that setting to a higher number? Also what version of the extension are you using?
![20220414-asbplayer-issue](https://user-images.githubusercontent.com/2254858/163511255-2d0f0659-1455-4b04-b442-3b2b3d623497.png)

**Comment by nzarbayezid** [comment] 2022-04-15 09:27
no bro that's not the problem, as I told you I tried many ways to fix it but it's the extension

**Comment by killergerbah** [comment] 2022-04-15 19:16
@nzarbayezid Thanks for replying. I suggested a possible way to fix the issue as you did not specify exactly what you had already attempted in order to fix the problem. 

If you have time it would be helpful if you pasted a screenshot of the DOM elements of the page where you're seeing the issue. Specifically it would be helpful to know which element is overflowing the bottom of the page. You can access the DOM elements by right clicking on the page and clicking 'Inspect element.'

**Comment by nzarbayezid** [comment] 2022-04-15 21:38
![Screenshot 2022-04-16 003427](https://user-images.githubusercontent.com/101425664/163635029-eb36e505-d70c-4569-9196-516fa24713d0.png)

![Screenshot 2022-04-16 003830](https://user-images.githubusercontent.com/101425664/163635137-794e6d33-12d7-4489-98af-79976ee5fb4f.png)

**Comment by killergerbah** [comment] 2022-04-15 23:54
@nzarbayezid awesome thanks, do you think you could click through the elements and try to highlight the elements at the bottom? If you can highlight the element that's going off the screen that would be great.

**Comment by killergerbah** [comment] 2022-04-16 02:03
@nzarbayezid Also, would be nice to see if the problem is the drop zone. If you drag a file into the Netflix player, does the dark asbplayer overlay go past the edge of the window? I attached a video of what it looks like for me. 

https://user-images.githubusercontent.com/2254858/163657370-988cbc54-b911-4714-b85e-2bcab99987c1.mp4

**Comment by nzarbayezid** [comment] 2022-04-16 09:13
https://user-images.githubusercontent.com/101425664/163669267-91a85261-acd1-45a9-972a-50d5ac552d1a.mp4

if you want any more information you can ask, I will answer you happily my dude

**Comment by nzarbayezid** [comment] 2022-04-16 09:18
>  If you drag a file into the Netflix player, does the dark asbplayer overlay go past the edge of the window? 

![IMG_20220416_121607](https://user-images.githubusercontent.com/101425664/163669470-ea359259-cf14-4d01-b8a2-2368a46f77a9.jpg)

**Comment by killergerbah** [comment] 2022-04-16 17:28
@nzarbayezid Thanks for all the help. I've attached two different versions of the extension. One is the latest version and the other has a workaround for your problem (as I don't know the root cause). If you have time, let me know if the first, the second, both, or none of them fix the issue.

[asbplayer-extension-0.18.0-snapshot.zip](https://github.com/killergerbah/asbplayer/files/8500368/asbplayer-extension-0.18.0-snapshot.zip)
[asbplayer-extension-0.18.0-snapshot-overflow-fix.zip](https://github.com/killergerbah/asbplayer/files/8500370/asbplayer-extension-0.18.0-snapshot-overflow-fix.zip)

**Comment by nzarbayezid** [comment] 2022-04-17 03:58
thanks

https://user-images.githubusercontent.com/101425664/163699749-945e5ea1-bc9d-48ab-aadd-d6fbe43fec29.mp4

**Comment by killergerbah** [comment] 2022-04-21 04:34
Going to go ahead and close this since it seems to be resolved.
I think for some reason the Netflix video element seems to be extending past the bottom of the screen in your case. At the moment there isn't a reason to believe that asbplayer is the thing that's causing that to happen.

**Closed by killergerbah** 2022-04-21 04:34 UTC
Labels: bug
