### ISSUE TITLE
Subtitles not found correctly in Emby in latest dev version

### ISSUE THREAD

**Issue by jonathanluepfert** [killergerbah/asbplayer#517] opened 2024-09-19 21:15 UTC
In the release version 1.4.2 it works fine, but when building the extension myself to get Jellyfin support working the extension breaks with Emby. The episode name is not being detected correctly, it shows the name of the series instead and finds no subtitle files.

**Comment by killergerbah** [comment] 2024-09-20 23:30
I just tried reproducing this myself and was unable to. Tagging @bpwhelan since he made the most recent changes to Emby subtitle detection.

**Comment by bpwhelan** [comment] 2024-09-20 23:34
I will check tonight when i get home.

**Comment by bpwhelan** [comment] 2024-09-21 04:03
Jellyfin seems to be even more broken than Emby for me, were you able to get the Jellyfin stuff to work @jonathanluepfert ?

**Comment by jonathanluepfert** [comment] 2024-09-21 04:09
Yeah I got the subtitles to load in Jellyfin just fine.

**Comment by bpwhelan** [comment] 2024-09-21 04:30
Going to combine these two into one file, they are way too similar, and default to the same port. Better than tearing up the whole page match logic.

**Comment by killergerbah** [comment] 2024-09-22 01:05
https://github.com/killergerbah/asbplayer/pull/520 is now merged thanks @bpwhelan 

Will be good to see if this fixes your issue @jonathanluepfert

**Closed** 2024-10-19 02:38 UTC
