### ISSUE TITLE
Unable to add multiple subtitles into asbplayer

### ISSUE THREAD

**Issue by bsumhz** [killergerbah/asbplayer#427] opened 2024-05-21 11:39 UTC
Hi,

I want to use asbplayer for multiple subtitles (eng/jap).
When I drag and drop (external) subtitle files in the player, only 1 set of subtitles will show at a time. If I drag and drop a second set of subtitles into the player it will replace my first ones. 

When I press control+shift+f to load the "select subtitles" screen it shows that up to 3 different subtitle tracks can be added. If I click "open file" to manually load the track, the "select subtitles" screen will automatically disappear once 1 set of subtitles have been added. If I press control+shift+f again, the tracks show as "all empty" even if I have 1 set of subtitles running on the video. 

How can I fix this?

Note: It works if pre-loaded subtitles are already available in the video. For example, on Youtube, if the Youtuber has multiple subtitles available in their video. I can select up to 3 different tracks no problem.

Also, is there a way to display furigana automatically on the Japanese subtitles instead of looking up via Yomichan?

Thank you for your hard work on the app! :)

**Comment by killergerbah** [comment] 2024-05-24 03:42
@bsumhz To load multiple files at the same time select multiple files when using the file selector, or simultaneously drag-and-drop multiple files onto the video element.

The subtitle track selector can be improved so that each menu has a separate 'open file' option. There is already an issue in the backlog for this.

**Comment by xpire** [comment] 2024-06-10 02:46
Duplicate of #380

**Comment by xpire** [comment] 2024-06-10 02:47
Furigana is a cool idea but it was asked before [here](https://github.com/killergerbah/asbplayer/issues/126). I guess we should close this for now?

**Closed** 2024-06-10 04:22 UTC
